### ISSUE TITLE
File missing | Can you please upload 

### ISSUE THREAD

**Issue by Rutulpatel7077** [ching56/relationship-visualization#1]
with open('

> /Users/Ching/Desktop/trans.json

','r', encoding='latin1') as f:
		data = json.load(f)

map = {}

for index in data["resource"]["events"]:
		name = index.get('character','NA')
		if name=='NA':
				continue
		addinf(name,index["when"][0],index["when"][1],map)

**Comment by ching56** [comment]
Hi @Rutulpatel7077 , I am sorry that I lost the file. 
But if you are still interesting in this topic,  [this Article](https://www.curiousgnu.com/movie-character-screen-time)  may be helpful.
Thanks for your message🙂
